### ISSUE TITLE
Running RetroSeq on heterozygous data

### ISSUE THREAD

**Issue by jacau** [wtsi-svi/RetroSeq#11]
I'm using the latest version RetroSeq (1.5) and when I run -call with -hets I get an error that it's not a valid option. Is the latest version altered to handle heterozygous data by default?

**Comment by oiiio** [comment]
About a year later, I am having this same question. The hets seem to be handled in code, but the README still mentions the parameter and it would be nice to have an answer from the author

**Comment by afadda91** [comment]
same question. still no answer?

**Comment by tk2** [comment]
Hi - yes, the later versions will detect het calls by default. Apologies for the late reply.
