### ISSUE TITLE
Is RetroSeq still able to handle split reads?

### ISSUE THREAD

**Issue by pyrevo** [wtsi-svi/RetroSeq#14]
Dear @tk2,

I'm starting to use RetroSeq v1.5. From my understanding, the program is able to search for split reads using the -srmode parameter. However when I print out the help page from the discover function of RetroSeq 1.5, I obtain a different set of parameters with respect to the tutorial page of the Wiki.

Thus, I'm wondering if this version of RetroSeq is still able to handle split reads.

Thanks,
Massimiliano.

**Comment by tk2** [comment]
Hi - yes it will now use split reads by default, no need to specify it on the command line.
