### ISSUE TITLE
FATAL ERROR : Unrecognised symbol

### ISSUE THREAD

**Issue by Leelouh** [wtsi-svi/RetroSeq#15]
Hi everybody!

I have an issue with RetroSeq : 

> ** FATAL ERROR **: Unrecognised symbol 'x' (ascii:120) file:[17846.allrefs.fasta] seq:[Endogenous_retrovirus] pos:[204]
exiting ...

I checked the file and saw that in fact there are some x, k, etc. In my fasta file where are the TE sequences.
How can I deal with it?

Thank you for your help!
Lou

**Comment by afadda91** [comment]
i have the same issue. i downloaded the fasta file from GIRI Repbase.

**Comment by tk2** [comment]
I think if you convert all non ACGT to N, then it will work.
