### ISSUE TITLE
hets option for the calling phase

### ISSUE THREAD

**Issue by Milad021** [wtsi-svi/RetroSeq#20]
Dear Mr. Keane,

I am currently analyzing about 50 samples and I have used the **-hets** option. However in the end, by analyzing my vcf file I only find homozygotes. 

I have ran the following command : 

**`retroseq.pl -call -depth 10000 -reads 3 -q 30 -hets -bam $path_bam_file -input candidats.tab -ref /data/UMD3_1.fa -filter /data/types.tab -output sample_HET.vcf`**

**> 1/1:20:8:0:4:3** (in my vcf file). 

In my other samples I only find homozygotes instead of heterozygotes like 1/1.
Is this normal?

Best reagards,

Milad

**Comment by tk2** [comment]
Hi - the -hets option is not active in the current version. I added it  to an earlier version and found after testing that it didn't work very well, so I removed it until the accuracy could be improved.

Rgds,
Thomas
